### ISSUE TITLE
False Positives in Errors

### ISSUE THREAD

**Issue by zoffixznet** [finanalyst/ModuleCitation#2]
The [errors section](https://finanalyst.github.io/ModuleCitation/#errorsprocessing) contains several false positives. I notice all of them have `:ver<>` or `:auth<>` adverbs in the name.

I suspect the code doesn't strip those before checking whether a module exists, but it should.

**Comment by finanalyst** [comment]
Zoffix,

Thanks for both responses. Replying to both here.

a) I will strip off the adverbs. ...

But I was thinking about whether the adverbs should be in the name in in 
the meta file. Surely the meta file is about meta information, which is 
what the adverbs represent.

b) The page is on git hub. The repo is there too. Not quite sure what 
you are suggesting.

Richard

**Comment by finanalyst** [comment]
Done this. Thanks for help.

It made a difference for the citation index of Json::tiny. So 
recalibrating archived data.

Richard

**Comment by zoffixznet** [comment]
a) Yeah they shoulf be, as they indicate a specific version/auth of the module. All of the false positives are present in the ecosystem, but they were still listed as missing.

b) I'm suggesting the page includes *a link* to the repo. The way I got here is by knowing how to construct a repo link from github pages link.
