### ISSUE TITLE
teach the script about cpan distributions

### ISSUE THREAD

**Issue by timo** [finanalyst/ModuleCitation#4]
Folks are gradually moving their modules onto cpan now - I've already moved JSON::Fast for example - and it'd be good if the citation script also grabbed data from there. Zef uses an index for cpan that can be found here: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json

**Comment by finanalyst** [comment]
modified so that config file has array of urls, not one url for location of modules.

**Comment by finanalyst** [comment]
looked at results and there are obvious errors. The modification has jiggered the data.

**Comment by finanalyst** [comment]
The addition of a second file with metadata (viz., two lists containing META6.json data) highlighted the fact that my original analysis only dealt with one structure of the `depends` field, as per S22. So, a major refactoring was required, as well as new tests to cover different structures. It has taken some time to get this working and tested.  Hopefully the software is now working well enough to create a chron task and update more regularly.

I am closing this issue.
